public enum SoundEffect : byte {
    //CURRENT HIGHEST NUMBER: 120 (use 121 next)
    //Enemy
    Enemy_Generic_Freeze = 0,
    Enemy_Generic_FreezeShatter = 1,
    Enemy_Generic_FreezeMelt = 105,
    Enemy_Generic_Stomp = 2,
    Enemy_Boo_Laugh = 101,
    Enemy_Bobomb_Explode = 3,
    Enemy_Bobomb_Fuse = 4,
    Enemy_BulletBill_Shoot = 5,
    Enemy_PiranhaPlant_Chomp = 7,
    Enemy_PiranhaPlant_Death = 6,
    Enemy_Shell_Kick = 8,
    Enemy_Shell_Combo1 = 9,
    Enemy_Shell_Combo2 = 10,
    Enemy_Shell_Combo3 = 11,
    Enemy_Shell_Combo4 = 12,
    Enemy_Shell_Combo5 = 13,
    Enemy_Shell_Combo6 = 14,
    Enemy_Shell_Combo7 = 15,

    //Player
    Player_Sound_Collision = 17,
    Player_Sound_Collision_Fireball = 18,
    Player_Sound_Crouch = 19,
    Player_Sound_Death = 20,
    Player_Sound_DeathOthers = 94,
    Player_Sound_Drill = 21,
    Player_Sound_GroundpoundStart = 22,
    Player_Sound_GroundpoundLanding = 23,
    Player_Sound_Jump = 24,
    Player_Sound_LavaHiss = 90,
    Player_Sound_PowerupCollect = 16,
    Player_Sound_PowerupReserveStore = 25,
    Player_Sound_PowerupReserveUse = 26,
    Player_Sound_Powerdown = 27,
    Player_Sound_Respawn = 28,
    Player_Sound_SlideEnd = 92,
    Player_Sound_Swim = 96,
    Player_Sound_WallJump = 29,
    Player_Sound_WallSlide = 30,

    Player_Walk_Grass = 31,
    Player_Walk_Snow = 32,
    Player_Walk_Sand = 93,
    Player_Walk_Water = 95,

    Player_Voice_DoubleJump = 33,
    Player_Voice_LavaDeath = 34,
    Player_Voice_MegaMushroom = 35,
    Player_Voice_Selected = 36,
    Player_Voice_SpinnerLaunch = 37,
    Player_Voice_TripleJump = 38,
    Player_Voice_WallJump = 39,
    Player_Sound_MegaMushroom_Collect = 40,
    Player_Voice_Pickup_Small = 115,
    Player_Voice_Pickup_Large = 116,
    Player_Voice_Throw_Small = 117,
    Player_Voice_Throw_Large = 118,
    Player_Voice_Taunt = 120,

    //Powerup
    Powerup_1UP_Collect = 78,
    Powerup_BlueShell_Enter = 41,
    Powerup_BlueShell_Slide = 42,
    Powerup_Fireball_Break = 43,
    Powerup_Fireball_Shoot = 44,
    Powerup_Iceball_Break = 46,
    Powerup_Iceball_Shoot = 47,
    Powerup_MegaMushroom_Break_Block = 48,
    Powerup_MegaMushroom_Break_Pipe = 49,
    Powerup_MegaMushroom_End = 50,
    Powerup_MegaMushroom_Groundpound = 51,
    Powerup_MegaMushroom_Jump = 52,
    Powerup_MegaMushroom_Walk = 53,
    Powerup_MiniMushroom_Collect = 45,
    Powerup_MiniMushroom_Groundpound = 54,
    Powerup_MiniMushroom_Jump = 55,
    Powerup_MiniMushroom_WaterWalk = 97,
    Powerup_PropellerMushroom_Drill = 56,
    Powerup_PropellerMushroom_Kick = 57,
    Powerup_PropellerMushroom_Spin = 58,
    Powerup_PropellerMushroom_Start = 59,
    Powerup_HammerSuit_Throw = 106, //HARDCODED: DO NOT CHANGE WITHOUT CHANGING POWERUPS SCRIPTABLES
    Powerup_HammerSuit_Bounce = 109,

    //UI Sounds / Songs / Jingles
    UI_HurryUp = 60,
    UI_Loading = 61,
    UI_Match_Lose = 62,
    UI_Match_Win = 63,
    UI_Match_Draw = 87,
    UI_Match_Cancel = 107,
    UI_Pause = 64,
    UI_Quit = 65,
    UI_StartGame = 66,
    UI_PlayerConnect = 79,
    UI_PlayerDisconnect = 80,
    UI_Decide = 81,
    UI_Back = 82,
    UI_Cursor = 83,
    UI_Error = 84,
    UI_WindowClose = 85,
    UI_WindowOpen = 86,
    UI_Countdown_0 = 88,
    UI_Countdown_1 = 89,
    UI_FileSelect = 98,
    UI_Chat_KeyUp = 102,
    UI_Chat_KeyDown = 103,
    UI_Chat_FullType = 108,
    UI_Chat_Send = 104,

    //World Elements
    World_Block_Break = 67,
    World_Block_Bump = 68,
    World_Block_Powerup = 69, // Nice
    World_Block_Powerup_Mega = 99,
    World_Coin_Collect = 70,
    World_Coin_Drop = 91,
    World_Coin_Dotted_Spawn = 100,
    World_Ice_Skidding = 71,
    World_Gold_Block_Damage = 112,
    World_Gold_Block_Equip = 113,
    World_Gold_Block_Finished = 114,
    World_Pipe_Use = 119,
    World_Spinner_Launch = 72,
    World_Starcoin_Collect = 110,
    World_Starcoin_Store = 111,
    World_Star_Collect = 73,
    World_Star_CollectOthers = 74,
    World_Star_Nearby = 75,
    World_Star_Spawn = 76,
    World_Water_Splash = 77,
}